# Generated by Django 5.2.4 on 2025-08-16 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Absent',
            fields=[
                ('absent_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('time_in', models.DateTimeField(blank=True, null=True)),
                ('time_out', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Absent',
                'verbose_name_plural': 'Absents',
                'db_table': 'absent',
            },
        ),
    ]
