# Generated by Django 5.2.4 on 2025-08-17 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('room', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('record_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('record_start', models.TimeField()),
                ('record_complete', models.TimeField()),
                ('room', models.ForeignKey(db_column='room_id', on_delete=django.db.models.deletion.CASCADE, related_name='service_records', to='room.room')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='service_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Record',
                'verbose_name_plural': 'Records',
                'db_table': 'record',
            },
        ),
        migrations.CreateModel(
            name='TaskMonitoring',
            fields=[
                ('tm_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tm_status', models.CharField(max_length=50)),
                ('record', models.ForeignKey(db_column='record_id', on_delete=django.db.models.deletion.CASCADE, related_name='task_monitorings', to='service.record')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='task_monitorings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task Monitoring',
                'verbose_name_plural': 'Task Monitorings',
                'db_table': 'task_monitoring',
            },
        ),
    ]
