# Generated by Django 5.2.4 on 2025-08-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='record_complete',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
