# Generated by Django 5.2.4 on 2025-08-01 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(blank=True, max_length=255, null=True)),
                ('room_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomRecord',
            fields=[
                ('rr_id', models.AutoField(primary_key=True, serialize=False)),
                ('guest_status', models.CharField(blank=True, max_length=255, null=True)),
                ('cleanliness_status', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='room.room')),
            ],
        ),
    ]
